
import "./globals.css";
import Headerstrip from "@/components/headerstrip";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Contactus from "@/components/contactus";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="bg-[#F0FFFE]">
        <Headerstrip />
        <Navbar />
        {children}
        <Contactus />
        <Footer />
      </body>
    </html>
  );
}
