
import "./globals.css";
import Headerstrip from "@/components/headerstrip";
import Navbar from "@/components/navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="bg-[#F0FFFE]">
        <Headerstrip />


        <Navbar />

        {children}

      </body>
    </html>
  );
}
