
import "./globals.css";
import Headerstrip from "@/components/headerstrip";
import Navbar from "@/components/navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="bg-[#F0FFFE]">
        <Headerstrip />
        <div className=" w-full flex items-center justify-center sticky top-0 z-50">

          <Navbar />
        </div>
        {children}

      </body>
    </html>
  );
}
